# Site settings
title: Charlie Jaime Designer | Developer
email: baroonie10@gmail.com
description: > # this means to ignore newlines until "baseurl:"
url: "cjbeowulf.github.io" # the base hostname & protocol for your site
twitter_username: cjbeowulf
github_username:  cjbeowulf
codepen_username: cjbeowulf
linkedin_username: charliejaime
# Build settings
markdown: kramdown
permalink: /:title

# Defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      category: "Programming"
      author: "Charlie Jaime"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "drafts"
    values:
      layout: "post"
